from email import message
import smtplib
mail = smtplib.SMTP('smtp.gmail.com' , '587')
mail.starttls()
mail.login('abc123@gmail.com' , '#############') #You must enter the password generated by gmail for third party apps, not of you gmail account.
message = "Hey there"
mail.sendmail("abc123@gmail.com" , "receiver@gmail.com" , message)
mail.quit()