import smtplib
sender_mail = input("enter your sender mail : ")
password = input("enter your sender mail password : ")
message = input("enter your message : ")
receiver_mail = input("enter receiver's mail : ")

mail = smtplib.SMTP('smtp.gmail.com' , '587')
mail.starttls()
mail.login( sender_mail , password) #You must enter the password generated by gmail for third party apps, not of your gmail account.

mail.sendmail( sender_mail, receiver_mail, message)


mail.quit()
print("mail sent successfully")